apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: osac-shared-base

resources:
- namespace.yaml


# Common labels for all OSAC components
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: osac
- pairs:
    osac.openshift.io/project: shared
